version: "3"
services:
  front:
    image: nginx
    volumes:
      - /cafe_kouno_front/build/:/usr/share/nginx/html
    ports:
      - "80:80"
    tty: true
    networks:
      cafe-network:
        ipv4_address: 172.18.0.4
    depends_on:
      - back
networks:
  cafe-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
